[package]
name = "loader"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serialport = "4.0.1"
postcard = "0.7.2"
serde = { version = "1.0.127", default-features = false, features = ["derive"] }
